server:
  port: 8888

spring:
  application:
    name: ${NAME}
  rabbitmq:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USER_NAME}
    password: ${REDIS_USER_PASS}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URL}
          username: ${GIT_USER_NAME}
          password: ${GIT_USER_PASS}

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
